#!/usr/bin/env bash
# script configures an ubuntu server as follows:
# **** localhost resolves to 127.0.0.2
# **** facebook.com resolvs to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
cp -f ~/hosts.new etc/hosts

